CREATE TABLE lpdbwlpglm01devdev.gold_lego_edw.md_post_vast
(
    polnr_postalg_ts   TIMESTAMP COMMENT('POLNR_POSTALG_TS'),
    relnr_r            DECIMAL(5, 0) COMMENT('RELNR_R'),
    volgnr_p           DECIMAL(7, 0) COMMENT('VOLGNR_P'),
    ond_nr_p           DECIMAL(3, 0) COMMENT('OND_NR_P'),
    tep_code_p         DECIMAL(1, 0) COMMENT('TEP_CODE_P'),
    ltst_mut_dat_p     DATE COMMENT('LTST_MUT_DAT_P'),
    wap_code_p         DECIMAL(1, 0) COMMENT('WAP_CODE_P'),
    vorig_polisnr_p    DECIMAL(11, 0) COMMENT('VORIG_POLISNR_P'),
    aanvangs_dat_p     DATE COMMENT('AANVANGS_DAT_P'),
    byz_1_cd_red_hp    DECIMAL(1, 0) COMMENT('BYZ_1_CD_RED_HP'),
    aanvangs_dat_cd    DECIMAL(1, 0) COMMENT('AANVANGS_DAT_CD'),
    ct_polis_p         DECIMAL(3, 0) COMMENT('CT_POLIS_P'),
    djr_v_dat_p        DATE COMMENT('DJR_V_DAT_P'),
    opn_dat_post_p     DATE COMMENT('OPN_DAT_POST_P'),
    ltst_sal_dat_p     DATE COMMENT('LTST_SAL_DAT_P'),
    parttime_perc_p    DECIMAL(7, 4) COMMENT('PARTTIME_PERC_P'),
    ltst_sal_code_p    DECIMAL(3, 0) COMMENT('LTST_SAL_CODE_P'),
    ltst_sal_p         DECIMAL(9, 2) COMMENT('LTST_SAL_P'),
    parttime_perc_gew  DECIMAL(7, 4) COMMENT('PARTTIME_PERC_GEW'),
    parttime_perc_dt_p DECIMAL(7, 4) COMMENT('PARTTIME_PERC_DT_P'),
    rel_nr_rr_p        DECIMAL(5, 0) COMMENT('REL_NR_RR_P'),
    volg_nr_rr_p       DECIMAL(7, 0) COMMENT('VOLG_NR_RR_P'),
    rel_nr_uitruil_p   DECIMAL(5, 0) COMMENT('REL_NR_UITRUIL_P'),
    volg_nr_uitruil_p  DECIMAL(7, 0) COMMENT('VOLG_NR_UITRUIL_P'),
    afgel_wzp_verz_p   DECIMAL(7, 2) COMMENT('AFGEL_WZP_VERZ_P'),
    zcanceldt          DATE,
    zcancelfg          STRING,
    zvalidfrom         STRING
)