CREATE TABLE lpdbwlpglm01devdev.gold_lego_edw.md_post_vast
(
    polnr_postalg_ts   TIMESTAMP,
    relnr_r            DECIMAL(5, 0),
    volgnr_p           DECIMAL(7, 0),
    ond_nr_p           DECIMAL(3, 0),
    tep_code_p         DECIMAL(1, 0),
    ltst_mut_dat_p     DATE,
    wap_code_p         DECIMAL(1, 0),
    vorig_polisnr_p    DECIMAL(11, 0),
    aanvangs_dat_p     DATE,
    byz_1_cd_red_hp    DECIMAL(1, 0),
    aanvangs_dat_cd    DECIMAL(1, 0),
    ct_polis_p         DECIMAL(3, 0),
    djr_v_dat_p        DATE,
    opn_dat_post_p     DATE,
    ltst_sal_dat_p     DATE,
    parttime_perc_p    DECIMAL(7, 4),
    ltst_sal_code_p    DECIMAL(3, 0),
    ltst_sal_p         DECIMAL(9, 2),
    parttime_perc_gew  DECIMAL(7, 4),
    parttime_perc_dt_p DECIMAL(7, 4),
    rel_nr_rr_p        DECIMAL(5, 0),
    volg_nr_rr_p       DECIMAL(7, 0),
    rel_nr_uitruil_p   DECIMAL(5, 0),
    volg_nr_uitruil_p  DECIMAL(7, 0),
    afgel_wzp_verz_p   DECIMAL(7, 2),
    zcanceldt          DATE,
    zcancelfg          STRING,
    zvalidfrom         STRING
)